language: node_js
node_js:
  - "unstable"
  - "stable"
  - "0.10"
after_script:
  - npm run coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/6bda671292fdd142c12d
    on_success: change
    on_failure: always
    on_start: false
